# Generated by Django 5.0.3 on 2024-03-16 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.login')),
            ],
        ),
        migrations.CreateModel(
            name='SignedupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.projects')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.login', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
