# Generated by Django 5.0.3 on 2024-03-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('postcode', models.TextField(max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.login')),
            ],
        ),
    ]
