# Generated by Django 5.0.3 on 2024-03-17 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeduplist',
            name='projectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.project'),
        ),
    ]
