# Generated by Django 5.0.3 on 2024-03-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_signeduplist_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeduplist',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.login'),
        ),
    ]
