# Generated by Django 5.0.3 on 2024-03-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_signeduplist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelist',
            name='total_attendees',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='total_projects',
        ),
        migrations.RemoveField(
            model_name='whitelist',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='whitelist',
            name='walletAddress',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
